version: "2"
services:
  ctia:
    image: ctia:latest
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - kibana
      - elasticsearch
  redis:
    image: redis
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:1.7
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:4.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
  nginx:
    restart: always
    image: nginx:alpine
    volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    links:
      - ctia
      - kibana
      - elasticsearch
      - redis
