version: "2"
services:
  ctia:
    image: ctia:latest
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis-dev
      - kibana-dev
      - elasticsearch-dev
  redis-dev:
    image: redis
    ports:
      - "6379:6379"
  elasticsearch-dev:
    image: elasticsearch:1.7
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana-dev:
    image: kibana:4.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-dev:9200
    links:
      - elasticsearch-dev
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
